### ISSUE TITLE
about word embedding🙏

### ISSUE THREAD

**Issue by wildalmond** [Evan-Feng/UXSenti#1]
Did you use monolingual word embedding representations(word2vec or glove) in the experiment?
Look forward to your kind reply.

**Comment by yanlinf** [comment]
No, we did not use pretrained word embeddings for our main models (CLIDSA_min/CLIDSA_full/CLCDSA). Instead, we initialized the word embeddings with uniform distribution U[-0.01, 0.01]. However, a baseline model MWE did use pretrained embeddings (as mentioned in Sec. 5.3 in the paper). MWE used FastText embeddings aligned by the MUSE library.
