### ISSUE TITLE
您好，有两个问题想向您请教一下

### ISSUE THREAD

**Issue by kya18** [Evan-Feng/UXSenti#2]
（1）请问在训练结束时输出的Test acc (w/ early stop)和Test acc (w/o early stop)具体区别是什么呢？哪个作为模型在测试集上的最终准确率呀？（2）是将源语言和目标语言的无情感标签数据一起送入模型训练，然后在有标签的目标语言上测试吗？

**Comment by yanlinf** [comment]
您好！关于第一个问题，做early stopping会用到目标语言的标注数据，因此paper里报告的数字是w/o early stop的结果。关于第二个问题，训练时会用到源语言+目标语言的无标注数据和源语言的标注数据，在测试阶段会用到目标语言的标注数据。
